#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import asyncio
import os
import sys
import time
from pprint import pprint

from azure.eventhub.aio import EventHubConsumerClient
# from gcloud import datastore

AZURE_CONNECTION_STRING = os.environ["AZURE_CONNECTION_STRING"]
EVENTHUB_NAME = os.environ['EVENTHUB_NAME']
GCP_CREDS = os.environ['GCP_CREDS']
LOG_NAME = os.environ['LOG_NAME']

gcp_logger = None

import google
import google.cloud
from google.cloud import logging

# google_cloud_logging.write("test messgae")



# Development hack - set max_count to a non-zero value to only process
# that many events
max_count = 0
counter = 0

def iso_time():
    return time.strftime("%Y%m%dT%H%M%SZ",time.gmtime())

def debug_it(t):
    print("\nType: {}".format(type(t)))
    pprint(t)
    print('-' * 20)

async def on_event(partition_context, event):
    global counter

    # log it
    counter += 1
    event_as_dict = event.body_as_json()
    num_entries = len(event_as_dict["records"])
    times = event_as_dict["records"][0]["time"]
    print("{} {:3d} Received event from partition: {}; message of {:2d} "
                "records sent {}.".format(iso_time(), counter,
                partition_context.partition_id, num_entries, times))

    # relay it
    global gcp_logger
    gcp_logger.log_struct(event_as_dict)

    # debug code below
    global max_count
    if max_count and counter >= max_count: raise SystemExit(-33)


async def read_events():
    client = EventHubConsumerClient.from_connection_string(
        conn_str=AZURE_CONNECTION_STRING,
        consumer_group="$default",
        eventhub_name=EVENTHUB_NAME
    )
    async with client:
        await client.receive(
            on_event=on_event,
            on_error=on_error,
            on_partition_close=on_partition_close,
            on_partition_initialize=on_partition_initialize,
            starting_position="-1",  # "-1" is from the beginning of the partition.
        )


async def on_partition_initialize(partition_context):
    print("Partition: {} has been initialized.".format(partition_context.partition_id))


async def on_partition_close(partition_context, reason):
    print("{} Partition: {} has been closed, reason for closing: {}.".format(iso_time(), 
        partition_context.partition_id,
        reason
    ))


async def on_error(partition_context, error):
    if partition_context:
        print("{} An exception: {} occurred during receiving from Partition: {}.".format(iso_time(), 
            partition_context.partition_id,
            error
        ))
    else:
        print("{} An exception: {} occurred during the load balance process.".format(iso_time(), error))

def main(args):
    print("{} {}".format(iso_time(), args))

    # log into GCP
    global gcp_logger
    gcp_client = logging.Client.from_service_account_json(GCP_CREDS)
    gcp_logger = gcp_client.logger(LOG_NAME)
    t = gcp_logger.log_text("test message 3")

    # Azure Event Hub is the driver
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(read_events())
    except (SystemExit, KeyboardInterrupt):
        pass
    finally:
        loop.stop()
        loop.close()

if __name__ == '__main__':
    main(sys.argv[1:])

